version: '3.8'

services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blut_db
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:5.4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'Secret1'
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '6789:80'
    links:
      - 'postgres:postgres-server'
    depends_on:
      - postgres
