version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - '5432:5432'
    volumes:
      - ./src/DAL/db-seed.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'secret'
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '6789:80'
    links:
      - 'postgres:postgres-server'
    depends_on:
      - postgres
